kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cephfs
provisioner: ceph.com/cephfs
reclaimPolicy: Retain
parameters:
  monitors: 192.168.105.92:6789,192.168.105.93:6789,192.168.105.94:6789
  adminId: admin
  adminSecretName: ceph-admin-secret
  adminSecretNamespace: "kube-system"
  claimRoot: /volumes/kubernetes
